"""add preforge tables

Revision ID: 0e88b8e0b3c2
Revises: a9be345fbb4f
Create Date: 2026-01-02 16:56:21.521580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0e88b8e0b3c2'
down_revision: Union[str, None] = 'a9be345fbb4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preforge_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_preforge_tag_user_name')
    )
    op.create_index(op.f('ix_preforge_tags_id'), 'preforge_tags', ['id'], unique=False)
    op.create_index(op.f('ix_preforge_tags_user_id'), 'preforge_tags', ['user_id'], unique=False)
    op.create_table('preforge_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('pinned', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preforge_topics_id'), 'preforge_topics', ['id'], unique=False)
    op.create_index(op.f('ix_preforge_topics_user_id'), 'preforge_topics', ['user_id'], unique=False)
    op.create_table('preforge_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['preforge_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_preforge_items_id'), 'preforge_items', ['id'], unique=False)
    op.create_index(op.f('ix_preforge_items_topic_id'), 'preforge_items', ['topic_id'], unique=False)
    op.create_table('preforge_topic_tags',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['preforge_tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['preforge_topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'tag_id'),
    sa.UniqueConstraint('topic_id', 'tag_id', name='uq_preforge_topic_tag')
    )
    op.alter_column('categories', 'type',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('conversation_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conversation_users', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('uq_conv_user', 'conversation_users', ['user_id', 'conversation_id'])
    op.drop_constraint('conversation_users_user_id_fkey', 'conversation_users', type_='foreignkey')
    op.drop_constraint('conversation_users_conversation_id_fkey', 'conversation_users', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversation_users', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.alter_column('food_inventory', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('food_inventory', 'desired_quantity',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('forge_item_follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_forge_item_follows_id'), 'forge_item_follows', ['id'], unique=False)
    op.create_index(op.f('ix_forge_item_follows_identity'), 'forge_item_follows', ['identity'], unique=False)
    op.create_index(op.f('ix_forge_item_follows_item_id'), 'forge_item_follows', ['item_id'], unique=False)
    op.alter_column('forge_item_votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_forge_item_votes_id'), 'forge_item_votes', ['id'], unique=False)
    op.create_index(op.f('ix_forge_item_votes_item_id'), 'forge_item_votes', ['item_id'], unique=False)
    op.create_index(op.f('ix_forge_item_votes_voter_identity'), 'forge_item_votes', ['voter_identity'], unique=False)
    op.drop_index('ix_forge_items_legacy', table_name='forge_items')
    op.create_index(op.f('ix_forge_items_id'), 'forge_items', ['id'], unique=False)
    op.create_index(op.f('ix_forge_items_legacy_id'), 'forge_items', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_forge_items_legacy_table'), 'forge_items', ['legacy_table'], unique=False)
    op.create_index(op.f('ix_forge_pledges_id'), 'forge_pledges', ['id'], unique=False)
    op.create_index(op.f('ix_forge_pledges_item_id'), 'forge_pledges', ['item_id'], unique=False)
    op.create_index(op.f('ix_forge_pledges_user_id'), 'forge_pledges', ['user_id'], unique=False)
    op.alter_column('forge_votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_problem_notes_created_at'), 'problem_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_problem_notes_id'), 'problem_notes', ['id'], unique=False)
    op.alter_column('problems', 'votes_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('problems', 'followers_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('seed_events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('seed_events', 'delta',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('seed_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('seed_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_index('ix_seed_events_event_type', table_name='seed_events')
    op.drop_index('ix_seed_events_identity_created', table_name='seed_events')
    op.create_index(op.f('ix_seed_events_created_at'), 'seed_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_seed_events_id'), 'seed_events', ['id'], unique=False)
    op.create_index(op.f('ix_seed_events_identity'), 'seed_events', ['identity'], unique=False)
    op.create_index(op.f('ix_solution_notes_created_at'), 'solution_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_solution_notes_id'), 'solution_notes', ['id'], unique=False)
    op.add_column('volunteer_applications', sa.Column('name', sa.String(), nullable=False))
    op.add_column('volunteer_applications', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('volunteer_applications', 'status')
    op.drop_column('volunteer_applications', 'created_at')
    op.drop_column('volunteer_applications', 'volunteer_name')
    op.drop_column('volunteer_applications', 'volunteer_email')
    op.alter_column('volunteer_requests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer_requests', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'Pending'::text"),
               existing_nullable=True)
    op.add_column('volunteer_applications', sa.Column('volunteer_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('volunteer_applications', sa.Column('volunteer_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('volunteer_applications', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('volunteer_applications', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'Pending'::text"), autoincrement=False, nullable=True))
    op.drop_column('volunteer_applications', 'email')
    op.drop_column('volunteer_applications', 'name')
    op.drop_index(op.f('ix_solution_notes_id'), table_name='solution_notes')
    op.drop_index(op.f('ix_solution_notes_created_at'), table_name='solution_notes')
    op.drop_index(op.f('ix_seed_events_identity'), table_name='seed_events')
    op.drop_index(op.f('ix_seed_events_id'), table_name='seed_events')
    op.drop_index(op.f('ix_seed_events_created_at'), table_name='seed_events')
    op.create_index('ix_seed_events_identity_created', 'seed_events', ['identity', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_seed_events_event_type', 'seed_events', ['event_type'], unique=False)
    op.alter_column('seed_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('seed_events', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('seed_events', 'delta',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('seed_events', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('problems', 'followers_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('problems', 'votes_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_problem_notes_id'), table_name='problem_notes')
    op.drop_index(op.f('ix_problem_notes_created_at'), table_name='problem_notes')
    op.alter_column('forge_votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=True)
    op.drop_index(op.f('ix_forge_pledges_user_id'), table_name='forge_pledges')
    op.drop_index(op.f('ix_forge_pledges_item_id'), table_name='forge_pledges')
    op.drop_index(op.f('ix_forge_pledges_id'), table_name='forge_pledges')
    op.drop_index(op.f('ix_forge_items_legacy_table'), table_name='forge_items')
    op.drop_index(op.f('ix_forge_items_legacy_id'), table_name='forge_items')
    op.drop_index(op.f('ix_forge_items_id'), table_name='forge_items')
    op.create_index('ix_forge_items_legacy', 'forge_items', ['legacy_table', 'legacy_id'], unique=False)
    op.drop_index(op.f('ix_forge_item_votes_voter_identity'), table_name='forge_item_votes')
    op.drop_index(op.f('ix_forge_item_votes_item_id'), table_name='forge_item_votes')
    op.drop_index(op.f('ix_forge_item_votes_id'), table_name='forge_item_votes')
    op.alter_column('forge_item_votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.drop_index(op.f('ix_forge_item_follows_item_id'), table_name='forge_item_follows')
    op.drop_index(op.f('ix_forge_item_follows_identity'), table_name='forge_item_follows')
    op.drop_index(op.f('ix_forge_item_follows_id'), table_name='forge_item_follows')
    op.alter_column('forge_item_follows', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('food_inventory', 'desired_quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('food_inventory', 'quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_constraint(None, 'conversation_users', type_='foreignkey')
    op.drop_constraint(None, 'conversation_users', type_='foreignkey')
    op.create_foreign_key('conversation_users_conversation_id_fkey', 'conversation_users', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key('conversation_users_user_id_fkey', 'conversation_users', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_conv_user', 'conversation_users', type_='unique')
    op.alter_column('conversation_users', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('conversation_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('categories', 'type',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'food'::character varying"),
               existing_nullable=False)
    op.drop_table('preforge_topic_tags')
    op.drop_index(op.f('ix_preforge_items_topic_id'), table_name='preforge_items')
    op.drop_index(op.f('ix_preforge_items_id'), table_name='preforge_items')
    op.drop_table('preforge_items')
    op.drop_index(op.f('ix_preforge_topics_user_id'), table_name='preforge_topics')
    op.drop_index(op.f('ix_preforge_topics_id'), table_name='preforge_topics')
    op.drop_table('preforge_topics')
    op.drop_index(op.f('ix_preforge_tags_user_id'), table_name='preforge_tags')
    op.drop_index(op.f('ix_preforge_tags_id'), table_name='preforge_tags')
    op.drop_table('preforge_tags')
    # ### end Alembic commands ###
