"""Add cost to TranscriptionUsage

Revision ID: 1eb4856b6154
Revises: 079a3a5175c2
Create Date: 2025-04-13 17:47:07.237973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb4856b6154'
down_revision: Union[str, None] = '079a3a5175c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_usage', sa.Column('cost', sa.Float(), nullable=True))
    op.drop_column('transcription_usage', 'cost_usd')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcription_usage', sa.Column('cost_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('transcription_usage', 'cost')
    # ### end Alembic commands ###
