"""user id to memory

Revision ID: 3b3a769a917d
Revises: c20734c0453f
Create Date: 2025-07-29 15:40:10.655599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b3a769a917d'
down_revision: Union[str, None] = 'c20734c0453f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('lyra_daily_memory', sa.Column('user_id', sa.String(), index=True))
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###



def downgrade() -> None:
    op.drop_column('lyra_daily_memory', 'user_id')
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
