"""Add CommunityProject and CommunityProjectTask models

Revision ID: 426551781182
Revises: e56dc76c1fa5
Create Date: 2025-07-10 15:26:15.549802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '426551781182'
down_revision: Union[str, None] = 'e56dc76c1fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_projects_id'), 'community_projects', ['id'], unique=False)
    op.create_table('community_project_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['community_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_project_tasks_id'), 'community_project_tasks', ['id'], unique=False)
    op.add_column('project_tasks', sa.Column('assigned_user_id', sa.Integer(), nullable=True))
    op.add_column('project_tasks', sa.Column('status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'project_tasks', 'users', ['assigned_user_id'], ['id'])
    op.add_column('projects', sa.Column('community_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'community_id')
    op.drop_constraint(None, 'project_tasks', type_='foreignkey')
    op.drop_column('project_tasks', 'status')
    op.drop_column('project_tasks', 'assigned_user_id')
    op.drop_index(op.f('ix_community_project_tasks_id'), table_name='community_project_tasks')
    op.drop_table('community_project_tasks')
    op.drop_index(op.f('ix_community_projects_id'), table_name='community_projects')
    op.drop_table('community_projects')
    # ### end Alembic commands ###
