"""Double Check Problem Models

Revision ID: 438025285365
Revises: 45a7ab9742d2
Create Date: 2025-08-10 20:44:19.917077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '438025285365'
down_revision: Union[str, None] = '45a7ab9742d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forge_votes_id', table_name='forge_votes')
    op.create_index(op.f('ix_problem_follows_id'), 'problem_follows', ['id'], unique=False)
    op.alter_column('problem_votes', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('problem_votes_problem_id_fkey', 'problem_votes', type_='foreignkey')
    op.create_foreign_key(None, 'problem_votes', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.alter_column('problems', 'votes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('problems', 'followers_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_problems_created_at'), 'problems', ['created_at'], unique=False)
    op.drop_column('problems', 'tags')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_problems_created_at'), table_name='problems')
    op.alter_column('problems', 'followers_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('problems', 'votes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'problem_votes', type_='foreignkey')
    op.create_foreign_key('problem_votes_problem_id_fkey', 'problem_votes', 'problems', ['problem_id'], ['id'])
    op.alter_column('problem_votes', 'problem_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_problem_follows_id'), table_name='problem_follows')
    op.create_index('ix_forge_votes_id', 'forge_votes', ['id'], unique=False)
    # ### end Alembic commands ###
