"""Add user_id to Ramblings

Revision ID: 49ad974c558a
Revises: 564e566bcf61
Create Date: 2025-05-21 14:24:04.605439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ad974c558a'
down_revision: Union[str, None] = '564e566bcf61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ramblings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ramblings', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ramblings', type_='foreignkey')
    op.drop_column('ramblings', 'user_id')
    # ### end Alembic commands ###
