"""Add Solutions Models

Revision ID: 54e74999f5a5
Revises: 438025285365
Create Date: 2025-08-13 12:46:28.719692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e74999f5a5'
down_revision: Union[str, None] = '438025285365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('votes_count', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_created_at'), 'solutions', ['created_at'], unique=False)
    op.create_index(op.f('ix_solutions_id'), 'solutions', ['id'], unique=False)
    op.create_index(op.f('ix_solutions_problem_id'), 'solutions', ['problem_id'], unique=False)
    op.create_index(op.f('ix_solutions_status'), 'solutions', ['status'], unique=False)
    op.create_index(op.f('ix_solutions_title'), 'solutions', ['title'], unique=False)
    op.create_table('solution_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('identity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id', 'identity', name='uq_solution_follow_one')
    )
    op.create_index(op.f('ix_solution_follows_id'), 'solution_follows', ['id'], unique=False)
    op.create_index(op.f('ix_solution_follows_identity'), 'solution_follows', ['identity'], unique=False)
    op.create_index(op.f('ix_solution_follows_solution_id'), 'solution_follows', ['solution_id'], unique=False)
    op.create_table('solution_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_id', sa.Integer(), nullable=False),
    sa.Column('voter_identity', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solution_id'], ['solutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solution_id', 'voter_identity', name='uq_solution_vote_one')
    )
    op.create_index(op.f('ix_solution_votes_id'), 'solution_votes', ['id'], unique=False)
    op.create_index(op.f('ix_solution_votes_solution_id'), 'solution_votes', ['solution_id'], unique=False)
    op.create_index(op.f('ix_solution_votes_voter_identity'), 'solution_votes', ['voter_identity'], unique=False)
    op.add_column('problems', sa.Column('accepted_solution_id', sa.Integer(), nullable=True))
    op.add_column('problems', sa.Column('solved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'problems', 'solutions', ['accepted_solution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_column('problems', 'solved_at')
    op.drop_column('problems', 'accepted_solution_id')
    op.drop_index(op.f('ix_solution_votes_voter_identity'), table_name='solution_votes')
    op.drop_index(op.f('ix_solution_votes_solution_id'), table_name='solution_votes')
    op.drop_index(op.f('ix_solution_votes_id'), table_name='solution_votes')
    op.drop_table('solution_votes')
    op.drop_index(op.f('ix_solution_follows_solution_id'), table_name='solution_follows')
    op.drop_index(op.f('ix_solution_follows_identity'), table_name='solution_follows')
    op.drop_index(op.f('ix_solution_follows_id'), table_name='solution_follows')
    op.drop_table('solution_follows')
    op.drop_index(op.f('ix_solutions_title'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_status'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_problem_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_id'), table_name='solutions')
    op.drop_index(op.f('ix_solutions_created_at'), table_name='solutions')
    op.drop_table('solutions')
    # ### end Alembic commands ###
