"""add living plan section model

Revision ID: 60271165e30b
Revises: bd0b9b8cbb4b
Create Date: 2025-07-28 15:37:14.811769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60271165e30b'
down_revision: Union[str, None] = 'bd0b9b8cbb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('living_plan_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tasks', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_living_plan_sections_id'), 'living_plan_sections', ['id'], unique=False)
    op.create_index(op.f('ix_living_plan_sections_owner_email'), 'living_plan_sections', ['owner_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_living_plan_sections_owner_email'), table_name='living_plan_sections')
    op.drop_index(op.f('ix_living_plan_sections_id'), table_name='living_plan_sections')
    op.drop_table('living_plan_sections')
    # ### end Alembic commands ###
