"""Fix food inventory category relationships

Revision ID: 7b0d157cfa62
Revises: b20f6d755370
Create Date: 2025-03-16 10:54:37.836389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0d157cfa62'
down_revision: Union[str, None] = 'b20f6d755370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_inventory', sa.Column('items', sa.Text(), nullable=True))
    op.drop_column('food_inventory', 'ingredients')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_inventory', sa.Column('ingredients', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('food_inventory', 'items')
    # ### end Alembic commands ###
