"""Add layout_config to communities

Revision ID: 8eec083d7940
Revises: b5e99f91f2bd
Create Date: 2025-07-12 17:17:00.327809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eec083d7940'
down_revision: Union[str, None] = 'b5e99f91f2bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('layout_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'layout_config')
    # ### end Alembic commands ###
