"""Creating ForgeIdeaNote

Revision ID: 91eb799d9c39
Revises: 624d036f2740
Create Date: 2025-08-08 22:03:08.302274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91eb799d9c39'
down_revision: Union[str, None] = '624d036f2740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forge_idea_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['forge_ideas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forge_idea_notes_id'), 'forge_idea_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forge_idea_notes_id'), table_name='forge_idea_notes')
    op.drop_table('forge_idea_notes')
    # ### end Alembic commands ###
