"""remove_lyra_tables

Revision ID: 94be2ac16995
Revises: 571a293f47d4
Create Date: 2026-04-04 11:46:36.427896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '94be2ac16995'
down_revision: Union[str, None] = '571a293f47d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lyra_chat_log')
    op.drop_table('lyra_soul')
    op.drop_table('lyra_weekly_memory')
    op.drop_index('ix_lyra_daily_memory_user_id', table_name='lyra_daily_memory')
    op.drop_table('lyra_daily_memory')
    op.drop_table('lyra_short_term_memory')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   
    op.create_table('lyra_short_term_memory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('memory', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lyra_short_term_memory_pkey')
    )
    op.create_table('lyra_daily_memory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('day', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lyra_daily_memory_pkey'),
    sa.UniqueConstraint('day', name='lyra_daily_memory_day_key')
    )
    op.create_index('ix_lyra_daily_memory_user_id', 'lyra_daily_memory', ['user_id'], unique=False)
    op.create_table('lyra_weekly_memory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('week_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='lyra_weekly_memory_pkey'),
    sa.UniqueConstraint('week_start', name='lyra_weekly_memory_week_start_key')
    )
    op.create_table('lyra_soul',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tone', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('style', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('beliefs', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('memory', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lyra_soul_pkey')
    )
    op.create_table('lyra_chat_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('reply', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='lyra_chat_log_pkey')
    )
    # ### end Alembic commands ###
