"""create forge tables

Revision ID: a4e6238df396
Revises: b75ab6cacab1
Create Date: 2025-08-07 15:02:03.278760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4e6238df396'
down_revision: Union[str, None] = 'b75ab6cacab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forge_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['forge_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forge_votes_user_email'), 'forge_votes', ['user_email'], unique=False)
    op.create_table('forge_workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('idea_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['forge_ideas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forge_workers_user_email'), 'forge_workers', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forge_workers_user_email'), table_name='forge_workers')
    op.drop_table('forge_workers')
    op.drop_index(op.f('ix_forge_votes_user_email'), table_name='forge_votes')
    op.drop_table('forge_votes')
    # ### end Alembic commands ###
