"""adding conversation relationships

Revision ID: a8e740b6f59b
Revises: b41f091b7145
Create Date: 2025-08-09 13:49:35.196914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e740b6f59b'
down_revision: Union[str, None] = 'b41f091b7145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('conversation_users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('conversation_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_users_id'), 'conversation_users', ['id'], unique=False)
    op.add_column('inbox_messages', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.alter_column('inbox_messages', 'content',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Text(),
                    nullable=False)
    # Modify this line to include the USING clause
    op.alter_column('inbox_messages', 'user_id',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    existing_nullable=True,
                    postgresql_using='user_id::integer')  # Add USING clause to cast VARCHAR to INTEGER
    op.drop_index('ix_inbox_messages_user_id', table_name='inbox_messages')
    op.create_foreign_key(None, 'inbox_messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key(None, 'inbox_messages', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'inbox_messages', type_='foreignkey')
    op.drop_constraint(None, 'inbox_messages', type_='foreignkey')
    op.create_index('ix_inbox_messages_user_id', 'inbox_messages', ['user_id'], unique=False)
    op.alter_column('inbox_messages', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('inbox_messages', 'content',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('inbox_messages', 'conversation_id')
    op.drop_index(op.f('ix_conversation_users_id'), table_name='conversation_users')
    op.drop_table('conversation_users')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
