"""Add is_admin to community_members

Revision ID: b5e99f91f2bd
Revises: 1180c8c0bbbc
Create Date: 2025-07-12 16:12:35.441217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5e99f91f2bd'
down_revision: Union[str, None] = '1180c8c0bbbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_members', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community_members', 'is_admin')
    # ### end Alembic commands ###
