"""add read flag to inbox messages

Revision ID: bd0b9b8cbb4b
Revises: 57966afe177b
Create Date: 2025-07-22 11:58:42.482027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0b9b8cbb4b'
down_revision: Union[str, None] = '57966afe177b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_messages', sa.Column('read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inbox_messages', 'read')
    # ### end Alembic commands ###
