"""Fix grocery item list id

Revision ID: bda12db6ca7a
Revises: 49ad974c558a
Create Date: 2025-05-22 14:20:08.447531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda12db6ca7a'
down_revision: Union[str, None] = '49ad974c558a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_items', sa.Column('grocery_list_id', sa.Integer(), nullable=False))
    op.add_column('grocery_items', sa.Column('checked', sa.Boolean(), nullable=True))
    op.execute("ALTER TABLE grocery_items ALTER COLUMN quantity TYPE INTEGER USING quantity::integer")
    op.drop_constraint('grocery_items_list_id_fkey', 'grocery_items', type_='foreignkey')
    op.create_foreign_key(None, 'grocery_items', 'grocery_lists', ['grocery_list_id'], ['id'])
    op.drop_column('grocery_items', 'note')
    op.drop_column('grocery_items', 'list_id')
    op.drop_column('grocery_items', 'have')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_items', sa.Column('have', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('grocery_items', sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('grocery_items', sa.Column('note', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'grocery_items', type_='foreignkey')
    op.create_foreign_key('grocery_items_list_id_fkey', 'grocery_items', 'grocery_lists', ['list_id'], ['id'])
    op.alter_column('grocery_items', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('grocery_items', 'checked')
    op.drop_column('grocery_items', 'grocery_list_id')
    # ### end Alembic commands ###
