"""Add dream_machine_outputs table for real

Revision ID: c590b05eca0a
Revises: 1f18d9049d4d
Create Date: 2025-05-29 17:52:54.491381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c590b05eca0a'
down_revision: Union[str, None] = '1f18d9049d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dream_machine_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('mantra', sa.String(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dream_machine_outputs_id'), 'dream_machine_outputs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dream_machine_outputs_id'), table_name='dream_machine_outputs')
    op.drop_table('dream_machine_outputs')
    # ### end Alembic commands ###
