"""Added uploaded_at field to Transcription

Revision ID: d0ae4e650f64
Revises: 337ef47496d9
Create Date: 2025-03-15 17:01:52.728179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0ae4e650f64'
down_revision: Union[str, None] = '337ef47496d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.alter_column('transcriptions', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transcriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_transcriptions_filename', table_name='transcriptions')
    op.drop_constraint('transcriptions_user_id_fkey', 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'users', ['user_id'], ['id'])
    op.drop_column('transcriptions', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.create_foreign_key('transcriptions_user_id_fkey', 'transcriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_transcriptions_filename', 'transcriptions', ['filename'], unique=False)
    op.alter_column('transcriptions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transcriptions', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transcriptions', 'uploaded_at')
    # ### end Alembic commands ###
