"""Add mantra maker and next action

Revision ID: e14b74cd3d05
Revises: 45930dbec767
Create Date: 2025-05-24 11:21:45.258145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e14b74cd3d05'
down_revision: Union[str, None] = '45930dbec767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("journal_entries", sa.Column("mantra", sa.Text(), nullable=True))
    op.add_column("journal_entries", sa.Column("next_action", sa.Text(), nullable=True))
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("journal_entries", "mantra")
    op.drop_column("journal_entries", "next_action")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
