"""Add creator_id to project and task

Revision ID: 0c72a360784b
Revises: e7ae7cde3df5
Create Date: 2025-07-11 15:31:29.428034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c72a360784b'
down_revision: Union[str, None] = 'e7ae7cde3df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community_project_tasks', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'community_project_tasks', 'users', ['creator_id'], ['id'])
    op.add_column('community_projects', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'community_projects', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community_projects', type_='foreignkey')
    op.drop_column('community_projects', 'creator_id')
    op.drop_constraint(None, 'community_project_tasks', type_='foreignkey')
    op.drop_column('community_project_tasks', 'creator_id')
    # ### end Alembic commands ###
