"""add reflection field to journal entries

Revision ID: 45930dbec767
Revises: 72fa7d762ef0
Create Date: 2025-05-23 20:00:59.176857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45930dbec767'
down_revision: Union[str, None] = '72fa7d762ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("journal_entries", sa.Column("reflection", sa.Text(), nullable=True))
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column("journal_entries", "reflection")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
