"""Attempting To Fix Forge Models

Revision ID: 624d036f2740
Revises: 5acb943a8671
Create Date: 2025-08-08 21:19:48.370953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '624d036f2740'
down_revision: Union[str, None] = '5acb943a8671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forge_ideas', sa.Column('votes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forge_ideas', 'votes_count')
    # ### end Alembic commands ###
