"""Add summary_text field

Revision ID: a2206cd7ae94
Revises: a536bcb27d0f
Create Date: 2025-03-13 15:31:46.804500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2206cd7ae94'
down_revision: Union[str, None] = 'a536bcb27d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('summary_text', sa.Text(), nullable=True))
    op.alter_column('transcriptions', 'transcription_text',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transcriptions', 'transcription_text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('transcriptions', 'summary_text')
    # ### end Alembic commands ###
