"""Moved notes into ForgeIdea model

Revision ID: b41f091b7145
Revises: 5e942c615b48
Create Date: 2025-08-09 01:07:26.995505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b41f091b7145'
down_revision: Union[str, None] = '5e942c615b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_forge_idea_notes_id', table_name='forge_idea_notes')
    op.drop_table('forge_idea_notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forge_idea_notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('idea_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idea_id'], ['forge_ideas.id'], name='forge_idea_notes_idea_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='forge_idea_notes_pkey')
    )
    op.create_index('ix_forge_idea_notes_id', 'forge_idea_notes', ['id'], unique=False)
    # ### end Alembic commands ###
