"""Fix database

Revision ID: 337ef47496d9
Revises: ded3ab193ec4
Create Date: 2025-03-13 16:23:15.230841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337ef47496d9'
down_revision: Union[str, None] = 'ded3ab193ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcriptions', sa.Column('category', sa.String(), nullable=True))
    op.drop_constraint('transcriptions_user_id_fkey', 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.create_foreign_key('transcriptions_user_id_fkey', 'transcriptions', 'users', ['user_id'], ['id'])
    op.drop_column('transcriptions', 'category')
    # ### end Alembic commands ###
