"""Add user_id and user_email to ForgeVote

Revision ID: 3a48269975a1
Revises: 5e4fb877f522
Create Date: 2025-08-08 20:12:53.498572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a48269975a1'
down_revision: Union[str, None] = '5e4fb877f522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forge_votes', sa.Column('user_id', sa.String(), nullable=True))
    op.drop_index('ix_forge_votes_user_email', table_name='forge_votes')
    op.create_index(op.f('ix_forge_votes_id'), 'forge_votes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forge_votes_id'), table_name='forge_votes')
    op.create_index('ix_forge_votes_user_email', 'forge_votes', ['user_email'], unique=False)
    op.drop_column('forge_votes', 'user_id')
    # ### end Alembic commands ###
