"""Added name to conversation model

Revision ID: 599f25844eab
Revises: 7bef95c73109
Create Date: 2025-08-09 18:31:38.191878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '599f25844eab'
down_revision: Union[str, None] = '7bef95c73109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_conversations_name'), 'conversations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_name'), table_name='conversations')
    op.drop_column('conversations', 'name')
    # ### end Alembic commands ###
