"""Add vote back population

Revision ID: 5acb943a8671
Revises: 3a48269975a1
Create Date: 2025-08-08 20:28:26.051463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acb943a8671'
down_revision: Union[str, None] = '3a48269975a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forge_ideas', 'votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forge_ideas', sa.Column('votes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
