"""Add user_id foreign key to ForgeWorker

Revision ID: 5e4fb877f522
Revises: 4e357e02031c
Create Date: 2025-08-08 16:48:04.294263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4fb877f522'
down_revision: Union[str, None] = '4e357e02031c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forge_workers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'forge_workers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'forge_workers', type_='foreignkey')
    op.drop_column('forge_workers', 'user_id')
    # ### end Alembic commands ###
