"""Your migration message

Revision ID: 5e942c615b48
Revises: 31247856dc41
Create Date: 2025-08-09 00:45:22.040302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e942c615b48'
down_revision: Union[str, None] = '31247856dc41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forge_ideas', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forge_ideas', 'notes')
    # ### end Alembic commands ###
