"""Add cascade delete to community_chat_messages

Revision ID: be7cd4a53c44
Revises: 8eec083d7940
Create Date: 2025-07-13 11:32:50.048090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be7cd4a53c44'
down_revision: Union[str, None] = '8eec083d7940'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('community_chat_messages_community_id_fkey', 'community_chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'community_chat_messages', 'communities', ['community_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'community_chat_messages', type_='foreignkey')
    op.create_foreign_key('community_chat_messages_community_id_fkey', 'community_chat_messages', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###
